stages:
    - Test

Test unit-tests:
    stage: Test
    image: mikepantz/python_class:latest
    tags:
        - docker
    script:
        - cd tests
        - nosetests

.Test notebook:
    stage: Test
    image: mikepantz/python_class:latest
    tags:
        - docker
    script:
        - jupyter-nbconvert --to html --execute Assignment.ipynb
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
          - ./*.html
        expire_in: 1 week
